eureka:
  client:
    registerWithEureka:
      value: true
    fetchRegistry:
      value: true
    instance:
      hostname: 18.136.126.140
    serviceUrl:
      defaultZone: http://18.136.126.140:8761/eureka

resilience4j:
  retry:
    instances:
      post:
        maxRetryAttemps: 3
        waitDuration: 3s
      user:
        maxRetryAttemps: 5
        waitDuration: 3s
  ratelimiter:
    instances:
      post:
        limitForPeriod: 1
        limitRefreshPeriod: 2s
        timeoutDuration: 10s
      user:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 2s
