eureka:
  client:
    registerWithEureka:
      value: true
    fetchRegistry:
      value: true
    instance:
      hostname: 18.136.126.140
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
