eureka:
  client:
    registerWithEureka:
      value: true
    fetchRegistry:
      value: true
    instance:
      hostname: 18.136.126.140
    serviceUrl:
      defaultZone: http://18.136.126.140:8762/eureka

resilience4j:
  retry:
    instances:
      post:
        maxRetryAttemps: 5
        waitDuration: 5s
      user:
        maxRetryAttemps: 5
        waitDuration: 3s
  ratelimiter:
    instances:
      post:
        limitForPeriod: 1
        limitRefreshPeriod: 20s
        timeoutDuration: 1s
      user:
        limitForPeriod: 1
        limitRefreshPeriod: 3s
        timeoutDuration: 1s
