eureka:
  client:
    registerWithEureka:
      value: true
    fetchRegistry:
      value: true
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  retry:
    instances:
      post:
        maxRetryAttemps: 5
        waitDuration: 3s
      user:
        maxRetryAttemps: 5
        waitDuration: 3s
  ratelimiter:
    instances:
      post:
        limitForPeriod: 1
        limitRefreshPeriod: 2s
        timeoutDuration: 1s
      user:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 1s
